### ISSUE TITLE
Unable to resolve module `@react-native-community/async-storage`

### ISSUE THREAD

**Issue by Rafatcb** [aveq-research/localforage-asyncstorage-driver#9]
Hi,

Version 2.0 brings a new peer dependency: `@react-native-community/async-storage`. Is there a reason to use it instead of  `@react-native-async-storage/async-storage`?

There is a warning in [@react-native-community/async-storage npm package page](https://www.npmjs.com/package/@react-native-community/async-storage):

![image](https://user-images.githubusercontent.com/26308880/103026516-e35aeb80-4532-11eb-800a-b576fedb47f0.png)

**Comment by Goldziher** [comment]
Yes I am also encountering this problem. For now I settled to keep it as is in my own pacakge - to allow using this package as a dependency, but if this is not resolve I will have to drop this package and instead create my own driver. Here is my package: https://github.com/react-native-async-storage/async-storage

**Comment by fohletex** [comment]
Hi people,

Thanks for noting about the package deprecation. It seems as if we didn't note the organizational move which was done two month ago here: https://github.com/react-native-async-storage/async-storage/commit/ce4f970df773d47b08e1593880d5c7f90612725a - I will fix that of course and publish it in a new 3.x publication.

Concerning the dependency vs. peerDependency-discussion: I'd thought @kuasha420 's idea in #6 to use the actual AsyncStorage-Package as a peer dependency anyhow is a good idea at itself, since users might want to determine by themselves to define which package version of the AsyncStorage package should be used. That's why we released it in a new major version. If there is a demand, we can reset this behaviour to make the package as common dependency again.

Anyhow: If you feel that we should use the peerDependency again as a usual package dependency, feel free to discuss it here. I'd further opened the GitHub discussions area in this repository for such or related purposes.

Cheers!

**Comment by fohletex** [comment]
Hi again!

- Fixed with eafda8e9f96f7edd35253e8e263da189d6c5e4e2
- Published new major version 3.x
- Deprecated all versions < 3.x which depend on old `@react-native-community/async-storage` dependency.

Have a pleasent and healthy new year! :rocket:

**Comment by Rafatcb** [comment]
@fohletex thank you for fixing that!

Have a nice year 😄

**Comment by Rafatcb** [comment]
@Goldziher take a look at [patch-package](https://www.npmjs.com/package/patch-package), I've been using it to avoid adding another dependency and it works well.

**Comment by fohletex** [comment]
Thank you @Rafatcb !! Yes, I can definitely recommend patch-package for such short quick fixes. I also use it sometimes for certain projects internally ... Or do a PR if you think the change would help everybody in the community. :)
